version: "3.5"

services:
  web:
    image: bref/fpm-dev-gateway
    ports:
    - '8000:80'
    volumes:
    - ./application/:/var/task
    depends_on:
    - php
    environment:
      HANDLER: public/index.php

  php:
    build: .
    volumes:
    - ./application/:/var/task:ro

  mysql:
    image: mysql:5.7.23
    environment:
      MYSQL_DATABASE: forge
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
    - ./data/mysql/:/var/lib/mysql
    ports:
    - 3306:3306

  redis:
    image: redis:4.0.11-alpine
    volumes:
    - ./data/redis:/data
