version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.3-apache-node-browsers-legacy
      environment:
        FLASK_CONFIG: testing
    steps:
    - checkout
    - run:
        name: Install NPM
        command: |
          npm install
    - run:
        name: Install Composer
        command: |
          composer install
    - run:
        name: Install Application NPM
        command: |
          cd application
          npm install
    - run:
        name: Install Application Composer
        command: |
          cd application
          composer install
    - run:
        name: Install Serverless
        command: |
          sudo npm install -g serverless
    - run:
        name: Serverless deployment
        command: |
          BRANCH=$(echo $CIRCLE_BRANCH | sed -e 's/\//-/g')
          serverless deploy --stage $BRANCH
    - run:
        name: Run Smoke Tests
        command: |
          wget --content-on-error -qO- https://uersrr98nb.execute-api.eu-central-1.amazonaws.com/feature-smoke-test/smoke-test
