version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.3-apache-node-browsers-legacy
      environment:
        FLASK_CONFIG: testing
    steps:
    - checkout
    - run:
        name: Install NPM
        command: |
          npm install
    - run:
        name: Install Composer
        command: |
          composer install
    - run:
        name: Install Application NPM
        command: |
          cd application
          npm install
    - run:
        name: Install Application Composer
        command: |
          cd application
          composer install
    - run:
        name: Install Serverless
        command: |
          sudo npm install -g serverless
    - run:
        name: Serverless deployment
        command: |
          echo "export BRANCH=$(echo $CIRCLE_BRANCH | sed -e 's/\//-/g')" >> $BASH_ENV
          serverless deploy --stage $BRANCH
    - run:
        name: Run Smoke Tests
        command: |
          SLS_URL="$(serverless info --verbose  --stage $BRANCH | grep ServiceEndpoint | sed s/ServiceEndpoint\:\ //g)"
          echo "export SLS_URL=$SLS_URL" >> $BASH_ENV
          echo "run smoke test with ${SLS_URL}/smoke-test"
          wget --content-on-error -qO- ${SLS_URL}/smoke-test

